/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'github-page',
    'deploy-auto',
    'config-website',
    'config-homepage',
    'add-files',
    'adapt-logo',
    'update-version',
  ],
  api: [
    'cli',
    'docusaurus-core',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  tls: [
    "tls/hash-function",
    "tls/public-key-cryptography",
    "tls/ssl-tls-overview",
    "tls/symmetric-cryptography",
    "tls/asymmetric-cryptography",
    "tls/tls-handshake",
     {
      type: 'category',
      label: 'TLS Labs',
      collapsed: false,
      items: [
        'tls/create-certificates',
        'tls/openssl-labs',
        'tls/openssl-server',
        'tls/browser-authentication',
        'tls/mutual-authentication',
        'tls/grpc-auth-labs',
        'tls/node-mutual-auth',
      ],
    },
  ],
};

module.exports = sidebars;
